### ISSUE TITLE
How to get .png files for textures

### ISSUE THREAD

**Issue by Ian-Haas** [SilentChaos512/Tutorial-Mod#6]
This may be an elementary question but in the tutorial you said you copied the silver texture .png files from another project.  Can I just copy those from this project? and what directory do they go in in order to be accessed by the data generator?

Thanks

**Comment by SilentChaos512** [comment]
The textures can be found here: https://github.com/SilentChaos512/Tutorial-Mod/tree/1.16.x/src/main/resources/assets/tutorial/textures. The file and folder names need to match exactly. Be sure to make the changes to the build.gradle file [here](https://github.com/SilentChaos512/Tutorial-Mod/commit/1b4eb46fdba432b4a1e2d6141ed3be911d9c7376#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7) (lines 92-94) specifically.

**Comment by Ian-Haas** [comment]
Thanks so much.  It worked out great.  Thanks for the detailed tutorial.
