### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by RealYusufIsmail** [SilentChaos512/Tutorial-Mod#9]
https://gist.github.com/realyusufismail/a4ebe73b89d5bab19a2b7a14a524db4d

 when doing your toturial and runnung https://www.youtube.com/watch?v=mDM6ZWny4bw&t=395s
  
and there are no files in generated my code https://github.com/realyusufismail/custom-mod/tree/1.15.5-beta/src/main/java/com/Yusuf/bentenmobmod/data

**Comment by SilentChaos512** [comment]
As your log says, your block model generator is looking for a texture that
does not exist. Check that you named the PNG file correctly.

**Comment by RealYusufIsmail** [comment]
![Uploading Screenshot 2021-05-08 at 18.20.16.png…]()

**Comment by RealYusufIsmail** [comment]
<img width="105" alt="Screenshot 2021-05-08 at 18 20 16" src="https://user-images.githubusercontent.com/67903886/117547926-12798180-b02a-11eb-9b2e-4c94c610771c.png">

**Comment by RealYusufIsmail** [comment]
it is name correctly

**Comment by RealYusufIsmail** [comment]
https://github.com/realyusufismail/custom-mod/

**Comment by RealYusufIsmail** [comment]
were my mod is you can check

**Comment by RealYusufIsmail** [comment]
is this right
@Override
    protected void registerStatesAndModels() {
        simpleBlock(BlockInit.BLACK_DIAMOND_BLOCK.get());
       simpleBlock(BlockInit.BLACK_DIAMOND_ORE.get());
       simpleBlock(BlockInit.INFINITUM_ORE.get());

    }

**Comment by SilentChaos512** [comment]
Your black diamond block/ore textures are not on GitHub. Should be [here](https://github.com/realyusufismail/custom-mod/tree/1.16.5-offical-version/src/main/resources/assets/bentenmobmod/textures/blocks).
